services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: "mysql:9.2.0"
    environment:
      - MYSQL_ROOT_PASSWORD=pippo
      - MYSQL_DATABASE=Prenotazioni
    volumes:
      - ./repository:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"